# syntax=docker/dockerfile:experimental
FROM ubuntu as intermediate
LABEL stage=intermediate
RUN apt-get update      
RUN apt-get install -y git
RUN mkdir /appGit 
WORKDIR /appGit  
RUN cd /appGit       
RUN git clone https://github.com/Gruppe-B2-Webprogrammierung/Webprogrammierung-B2.git /appGit

FROM node:lts-alpine3.14
RUN mkdir /app
WORKDIR /app 
COPY --from=intermediate ./appGit .
ENV NODE_ENV=production
RUN npm install --production
ENV PORT=8080
EXPOSE 8080
CMD ["node", "app.js"]